### PR TITLE
Compatibility with rails 5 beta 2

### PR DESCRIPTION
**Pull request by jakoss**
All tests are passing (tested using ruby 2.3)

### CODE REVIEW

**Comment by jakoss** [comment]
I see need to bump ruby version to at least 2.2.2 for rack 2.0 to work

**Comment by phallguy** [comment]
Awesome thanks for the attention to this! I think I'd like to continue supporting rails 4. Would you mind taking another pass so that it supports 4 and 5?

**Comment by jakoss** [comment]
Sorry, my bad. Done ;)

**Comment by phallguy** [comment]
Perfect thanks for the help.

**Comment by jakoss** [comment]
Any plans to release new version of gem with this?

**Comment by phallguy** [comment]
done.

**Comment by jakoss** [comment]
Thanks :+1:

**Comment by scarroll32** [comment]
This was working for 5.0.0.rc2, but is failing on 5.0.0

**Comment by phallguy** [comment]
@seanfcarroll I don't have an app running 5.0 yet so don't really have an easy course to verify or test. I would imagine a fix would be pretty simple and would love a PR if you could manage. If not, please open a new issue and report the actual failure details so that I can take a look at them.

**Pull request merged**
